// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type Session struct {
	SessionID string
	UserID    int64
	ExpiresAt int64
}

type User struct {
	ID       int64
	Username string
	Password string
}
